# 指定Eureka服务器地址
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka,http://root:root@localhost:8762/eureka

# 指定服务的名称
spring:
  application:
    name: SEARCH

server:
  # 项目的端口
  port: 8082
  servlet:
    # 项目根路径
    context-path: /