# 指定Eureka服务器地址
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka,http://root:root@localhost:8762/eureka

# 指定服务的名称
spring:
  application:
    name: CUSTOMER

# 指定具体服务调用的负载均衡策略
SEARCH:    # 服务名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule

server:
  # 项目的端口
  port: 8081
  servlet:
    # 项目根路径
    context-path: /

# hystrix和feign整合，开启feign的fallback
feign:
  hystrix:
    enabled: true
